language: ruby
rvm:
  - "2.0.0"
  - "2.1.10"
  - "2.2.5"
  - "2.3.1"
before_install:
  - gem update --system
  - gem install bundler
services: mongodb
script:
  - bundle exec rake test
  - bundle exec codeclimate-test-reporter
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
addons:
    code_climate:
        repo_token: ac1640edaefa720557e56bfaba4e09808559d7d61812f96d58ea4aa5f4669738
